source 'https://github.com/CocoaPods/Specs.git'

target 'L360EventTracker', :exclusive => true do
  pod "L360EventTracker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "L360EventTracker", :path => "../"

  
end
